# Generated by Django 5.2.14 on 2026-05-12 03:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("projects", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Invoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("invoice_number", models.CharField(max_length=30, unique=True)),
                (
                    "invoice_type",
                    models.CharField(
                        choices=[
                            ("factura", "Factura de Venta"),
                            ("anticipo", "Anticipo"),
                            ("acta_cobro", "Acta de Cobro"),
                        ],
                        default="factura",
                        max_length=15,
                    ),
                ),
                ("issue_date", models.DateField()),
                ("due_date", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("borrador", "Borrador"),
                            ("enviada", "Enviada"),
                            ("pagada_parcial", "Pagada Parcialmente"),
                            ("pagada", "Pagada"),
                            ("vencida", "Vencida"),
                            ("anulada", "Anulada"),
                        ],
                        default="borrador",
                        max_length=15,
                    ),
                ),
                (
                    "subtotal",
                    models.DecimalField(decimal_places=2, default=0, max_digits=18),
                ),
                (
                    "tax_rate",
                    models.DecimalField(decimal_places=2, default=19, max_digits=5),
                ),
                (
                    "tax_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=18),
                ),
                (
                    "retention",
                    models.DecimalField(decimal_places=2, default=0, max_digits=18),
                ),
                (
                    "total",
                    models.DecimalField(decimal_places=2, default=0, max_digits=18),
                ),
                (
                    "paid_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=18),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Factura",
                "verbose_name_plural": "Facturas",
                "ordering": ["-issue_date"],
            },
        ),
        migrations.CreateModel(
            name="InvoiceItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.CharField(max_length=300)),
                ("unit", models.CharField(blank=True, max_length=30)),
                (
                    "quantity",
                    models.DecimalField(decimal_places=3, default=1, max_digits=12),
                ),
                ("unit_price", models.DecimalField(decimal_places=2, max_digits=14)),
                ("total", models.DecimalField(decimal_places=2, max_digits=16)),
            ],
            options={
                "verbose_name": "Ítem de Factura",
                "verbose_name_plural": "Ítems de Factura",
            },
        ),
        migrations.CreateModel(
            name="Journal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.CharField(max_length=30, unique=True)),
                ("date", models.DateField()),
                ("description", models.CharField(max_length=300)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("borrador", "Borrador"),
                            ("contabilizado", "Contabilizado"),
                            ("anulado", "Anulado"),
                        ],
                        default="borrador",
                        max_length=15,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("reference", models.CharField(blank=True, max_length=100)),
                ("notes", models.TextField(blank=True)),
            ],
            options={
                "verbose_name": "Comprobante Contable",
                "verbose_name_plural": "Comprobantes Contables",
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="JournalEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.CharField(max_length=300)),
                (
                    "debit",
                    models.DecimalField(decimal_places=2, default=0, max_digits=16),
                ),
                (
                    "credit",
                    models.DecimalField(decimal_places=2, default=0, max_digits=16),
                ),
            ],
            options={
                "verbose_name": "Movimiento Contable",
                "verbose_name_plural": "Movimientos Contables",
            },
        ),
        migrations.CreateModel(
            name="Account",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=20, unique=True)),
                ("name", models.CharField(max_length=200)),
                (
                    "account_type",
                    models.CharField(
                        choices=[
                            ("activo", "Activo"),
                            ("pasivo", "Pasivo"),
                            ("patrimonio", "Patrimonio"),
                            ("ingreso", "Ingreso"),
                            ("gasto", "Gasto"),
                            ("costo", "Costo"),
                        ],
                        max_length=15,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("description", models.TextField(blank=True)),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="children",
                        to="accounting.account",
                    ),
                ),
            ],
            options={
                "verbose_name": "Cuenta Contable",
                "verbose_name_plural": "Cuentas Contables",
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="Budget",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("materiales", "Materiales"),
                            ("mano_obra", "Mano de Obra"),
                            ("equipos", "Equipos y Maquinaria"),
                            ("combustible", "Combustible"),
                            ("transporte", "Transporte"),
                            ("subcontrato", "Subcontrato"),
                            ("administrativo", "Gastos Administrativos"),
                            ("seguridad", "Seguridad Industrial"),
                            ("otro", "Otro"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "budgeted_amount",
                    models.DecimalField(decimal_places=2, max_digits=18),
                ),
                (
                    "actual_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=18),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="budgets",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "verbose_name": "Presupuesto",
                "verbose_name_plural": "Presupuestos",
            },
        ),
        migrations.CreateModel(
            name="Expense",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("materiales", "Materiales"),
                            ("mano_obra", "Mano de Obra"),
                            ("equipos", "Equipos y Maquinaria"),
                            ("combustible", "Combustible"),
                            ("transporte", "Transporte"),
                            ("subcontrato", "Subcontrato"),
                            ("administrativo", "Gastos Administrativos"),
                            ("seguridad", "Seguridad Industrial"),
                            ("otro", "Otro"),
                        ],
                        max_length=20,
                    ),
                ),
                ("description", models.CharField(max_length=300)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=16)),
                ("expense_date", models.DateField()),
                ("invoice_number", models.CharField(blank=True, max_length=50)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pendiente", "Pendiente de Aprobación"),
                            ("aprobado", "Aprobado"),
                            ("rechazado", "Rechazado"),
                            ("pagado", "Pagado"),
                        ],
                        default="pendiente",
                        max_length=15,
                    ),
                ),
                (
                    "receipt",
                    models.FileField(blank=True, null=True, upload_to="expenses/"),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="expenses_approved",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="expenses",
                        to="projects.project",
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="expenses_requested",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Gasto",
                "verbose_name_plural": "Gastos",
                "ordering": ["-expense_date"],
            },
        ),
    ]
