# Generated by Django 5.2.14 on 2026-05-12 03:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("personnel", "0001_initial"),
        ("projects", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Equipment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=20, unique=True)),
                ("name", models.CharField(max_length=150)),
                (
                    "equipment_type",
                    models.CharField(
                        choices=[
                            ("excavadora", "Excavadora"),
                            ("bulldozer", "Bulldózer"),
                            ("motoniveladora", "Motoniveladora"),
                            ("compactador", "Compactador/Vibrocompactador"),
                            ("retroexcavadora", "Retroexcavadora"),
                            ("cargador", "Cargador Frontal"),
                            ("grua", "Grúa"),
                            ("concretera", "Concretera/Mezcladora"),
                            ("bomba_concreto", "Bomba de Concreto"),
                            ("camion_volqueta", "Camión Volqueta"),
                            ("camion_cisterna", "Camión Cisterna"),
                            ("camion_mixer", "Camión Mixer"),
                            ("camion_plataforma", "Camión Plataforma"),
                            ("camioneta", "Camioneta"),
                            ("otro", "Otro"),
                        ],
                        max_length=30,
                    ),
                ),
                ("brand", models.CharField(max_length=100)),
                ("model", models.CharField(max_length=100)),
                ("year", models.IntegerField(blank=True, null=True)),
                ("serial_number", models.CharField(blank=True, max_length=100)),
                ("plate", models.CharField(blank=True, max_length=20)),
                ("capacity", models.CharField(blank=True, max_length=50)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("disponible", "Disponible"),
                            ("asignado", "Asignado"),
                            ("mantenimiento", "En Mantenimiento"),
                            ("dañado", "Dañado"),
                            ("inactivo", "Inactivo"),
                        ],
                        default="disponible",
                        max_length=20,
                    ),
                ),
                (
                    "ownership",
                    models.CharField(
                        choices=[
                            ("propio", "Propio"),
                            ("alquilado", "Alquilado"),
                            ("leasing", "Leasing"),
                        ],
                        default="propio",
                        max_length=10,
                    ),
                ),
                ("purchase_date", models.DateField(blank=True, null=True)),
                (
                    "purchase_value",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=16, null=True
                    ),
                ),
                (
                    "current_hourmeter",
                    models.DecimalField(decimal_places=1, default=0, max_digits=10),
                ),
                (
                    "current_mileage",
                    models.DecimalField(decimal_places=1, default=0, max_digits=12),
                ),
                ("fuel_type", models.CharField(blank=True, max_length=20)),
                ("insurance_expiry", models.DateField(blank=True, null=True)),
                ("technical_review_expiry", models.DateField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "photo",
                    models.ImageField(blank=True, null=True, upload_to="equipment/"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Equipo",
                "verbose_name_plural": "Equipos",
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="EquipmentAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("activo", "Activo"),
                            ("finalizado", "Finalizado"),
                            ("cancelado", "Cancelado"),
                        ],
                        default="activo",
                        max_length=10,
                    ),
                ),
                (
                    "daily_rate",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "assigned_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="equipment_assignments_made",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "equipment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="assignments",
                        to="equipment.equipment",
                    ),
                ),
                (
                    "operator",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="equipment_assignments",
                        to="personnel.employee",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="equipment_assignments",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "verbose_name": "Asignación de Equipo",
                "verbose_name_plural": "Asignaciones de Equipo",
                "ordering": ["-start_date"],
            },
        ),
        migrations.CreateModel(
            name="EquipmentMaintenance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "maintenance_type",
                    models.CharField(
                        choices=[
                            ("preventivo", "Preventivo"),
                            ("correctivo", "Correctivo"),
                            ("predictivo", "Predictivo"),
                            ("cambio_aceite", "Cambio de Aceite"),
                            ("revision_general", "Revisión General"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("programado", "Programado"),
                            ("en_proceso", "En Proceso"),
                            ("completado", "Completado"),
                            ("cancelado", "Cancelado"),
                        ],
                        default="programado",
                        max_length=15,
                    ),
                ),
                ("scheduled_date", models.DateField()),
                ("completion_date", models.DateField(blank=True, null=True)),
                ("description", models.TextField()),
                ("performed_by", models.CharField(blank=True, max_length=200)),
                (
                    "cost",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=14, null=True
                    ),
                ),
                (
                    "hourmeter_at_maintenance",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=10, null=True
                    ),
                ),
                (
                    "next_maintenance_hourmeter",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=10, null=True
                    ),
                ),
                ("next_maintenance_date", models.DateField(blank=True, null=True)),
                ("parts_replaced", models.TextField(blank=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "equipment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="maintenances",
                        to="equipment.equipment",
                    ),
                ),
            ],
            options={
                "verbose_name": "Mantenimiento de Equipo",
                "verbose_name_plural": "Mantenimientos de Equipo",
                "ordering": ["-scheduled_date"],
            },
        ),
        migrations.CreateModel(
            name="FuelLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("gallons", models.DecimalField(decimal_places=2, max_digits=8)),
                ("unit_cost", models.DecimalField(decimal_places=2, max_digits=10)),
                ("total_cost", models.DecimalField(decimal_places=2, max_digits=14)),
                (
                    "hourmeter",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=10, null=True
                    ),
                ),
                (
                    "mileage",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=12, null=True
                    ),
                ),
                ("fuel_station", models.CharField(blank=True, max_length=150)),
                ("notes", models.TextField(blank=True)),
                (
                    "equipment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fuel_logs",
                        to="equipment.equipment",
                    ),
                ),
                (
                    "filled_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="fuel_logs_filled",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="fuel_logs",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "verbose_name": "Registro de Combustible",
                "verbose_name_plural": "Registros de Combustible",
                "ordering": ["-date"],
            },
        ),
    ]
