# Generated by Django 5.2.14 on 2026-05-12 03:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("equipment", "0001_initial"),
        ("personnel", "0001_initial"),
        ("projects", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LogPersonnel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "hours_worked",
                    models.DecimalField(decimal_places=2, default=8, max_digits=5),
                ),
                (
                    "extra_hours",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                ("task", models.CharField(max_length=200)),
                ("observations", models.TextField(blank=True)),
            ],
            options={
                "verbose_name": "Personal en Bitácora",
                "verbose_name_plural": "Personal en Bitácoras",
            },
        ),
        migrations.CreateModel(
            name="DailyLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                (
                    "weather_morning",
                    models.CharField(
                        choices=[
                            ("soleado", "Soleado"),
                            ("nublado", "Nublado"),
                            ("lluvia_leve", "Lluvia Leve"),
                            ("lluvia_fuerte", "Lluvia Fuerte"),
                            ("tormenta", "Tormenta"),
                        ],
                        default="soleado",
                        max_length=20,
                    ),
                ),
                (
                    "weather_afternoon",
                    models.CharField(
                        choices=[
                            ("soleado", "Soleado"),
                            ("nublado", "Nublado"),
                            ("lluvia_leve", "Lluvia Leve"),
                            ("lluvia_fuerte", "Lluvia Fuerte"),
                            ("tormenta", "Tormenta"),
                        ],
                        default="soleado",
                        max_length=20,
                    ),
                ),
                (
                    "temperature_min",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=5, null=True
                    ),
                ),
                (
                    "temperature_max",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=5, null=True
                    ),
                ),
                ("general_notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="daily_logs",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "verbose_name": "Bitácora Diaria",
                "verbose_name_plural": "Bitácoras Diarias",
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="LogActivity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.CharField(max_length=300)),
                ("location", models.CharField(blank=True, max_length=200)),
                (
                    "quantity",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("unit", models.CharField(blank=True, max_length=30)),
                ("start_time", models.TimeField(blank=True, null=True)),
                ("end_time", models.TimeField(blank=True, null=True)),
                (
                    "progress_percentage",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                ("observations", models.TextField(blank=True)),
                (
                    "daily_log",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activities",
                        to="logs.dailylog",
                    ),
                ),
            ],
            options={
                "verbose_name": "Actividad de Bitácora",
                "verbose_name_plural": "Actividades de Bitácora",
            },
        ),
        migrations.CreateModel(
            name="LogEquipment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "hours_operated",
                    models.DecimalField(decimal_places=2, default=0, max_digits=6),
                ),
                (
                    "hours_idle",
                    models.DecimalField(decimal_places=2, default=0, max_digits=6),
                ),
                ("activity", models.CharField(max_length=300)),
                (
                    "initial_hourmeter",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=10, null=True
                    ),
                ),
                (
                    "final_hourmeter",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=10, null=True
                    ),
                ),
                (
                    "fuel_consumed",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True
                    ),
                ),
                ("observations", models.TextField(blank=True)),
                (
                    "daily_log",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="equipment_entries",
                        to="logs.dailylog",
                    ),
                ),
                (
                    "equipment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="equipment.equipment",
                    ),
                ),
                (
                    "operator",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="personnel.employee",
                    ),
                ),
            ],
            options={
                "verbose_name": "Equipo en Bitácora",
                "verbose_name_plural": "Equipos en Bitácoras",
            },
        ),
        migrations.CreateModel(
            name="LogIncident",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "incident_type",
                    models.CharField(
                        choices=[
                            ("accidente", "Accidente de Trabajo"),
                            ("incidente", "Incidente"),
                            ("casi_accidente", "Casi Accidente"),
                            ("seguridad", "Seguridad Industrial"),
                            ("ambiental", "Ambiental"),
                            ("calidad", "Calidad"),
                            ("otro", "Otro"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("leve", "Leve"),
                            ("moderado", "Moderado"),
                            ("grave", "Grave"),
                            ("critico", "Crítico"),
                        ],
                        max_length=10,
                    ),
                ),
                ("description", models.TextField()),
                ("location", models.CharField(max_length=200)),
                ("persons_involved", models.TextField(blank=True)),
                ("immediate_actions", models.TextField(blank=True)),
                ("reported_to", models.CharField(blank=True, max_length=200)),
                ("time", models.TimeField(blank=True, null=True)),
                (
                    "daily_log",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="incidents",
                        to="logs.dailylog",
                    ),
                ),
            ],
            options={
                "verbose_name": "Incidente en Bitácora",
                "verbose_name_plural": "Incidentes en Bitácoras",
            },
        ),
        migrations.CreateModel(
            name="LogMaterial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity_used", models.DecimalField(decimal_places=3, max_digits=12)),
                ("unit", models.CharField(max_length=30)),
                ("activity", models.CharField(blank=True, max_length=200)),
                ("observations", models.TextField(blank=True)),
                (
                    "daily_log",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="material_entries",
                        to="logs.dailylog",
                    ),
                ),
            ],
            options={
                "verbose_name": "Material en Bitácora",
                "verbose_name_plural": "Materiales en Bitácoras",
            },
        ),
    ]
