# Generated by Django 5.2.14 on 2026-05-12 03:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("logs", "0001_initial"),
        ("personnel", "0001_initial"),
        ("warehouse", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="logmaterial",
            name="material",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="warehouse.material"
            ),
        ),
        migrations.AddField(
            model_name="logpersonnel",
            name="daily_log",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="personnel_entries",
                to="logs.dailylog",
            ),
        ),
        migrations.AddField(
            model_name="logpersonnel",
            name="employee",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="personnel.employee"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="dailylog",
            unique_together={("project", "date")},
        ),
    ]
