# Generated by Django 5.2.14 on 2026-05-12 03:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Department",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
            ],
            options={
                "verbose_name": "Departamento",
                "verbose_name_plural": "Departamentos",
            },
        ),
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("employee_code", models.CharField(max_length=20, unique=True)),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                (
                    "id_type",
                    models.CharField(
                        choices=[
                            ("cc", "Cédula de Ciudadanía"),
                            ("ce", "Cédula de Extranjería"),
                            ("pasaporte", "Pasaporte"),
                            ("nit", "NIT"),
                        ],
                        default="cc",
                        max_length=15,
                    ),
                ),
                ("id_number", models.CharField(max_length=30, unique=True)),
                ("birth_date", models.DateField(blank=True, null=True)),
                (
                    "blood_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("A+", "A+"),
                            ("A-", "A-"),
                            ("B+", "B+"),
                            ("B-", "B-"),
                            ("AB+", "AB+"),
                            ("AB-", "AB-"),
                            ("O+", "O+"),
                            ("O-", "O-"),
                        ],
                        max_length=3,
                    ),
                ),
                ("phone", models.CharField(blank=True, max_length=20)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("address", models.CharField(blank=True, max_length=300)),
                ("city", models.CharField(blank=True, max_length=100)),
                ("emergency_contact", models.CharField(blank=True, max_length=150)),
                ("emergency_phone", models.CharField(blank=True, max_length=20)),
                ("hire_date", models.DateField()),
                ("termination_date", models.DateField(blank=True, null=True)),
                (
                    "salary_type",
                    models.CharField(
                        choices=[
                            ("fijo", "Salario Fijo"),
                            ("variable", "Salario Variable"),
                            ("jornal", "Jornal"),
                            ("honorarios", "Honorarios"),
                        ],
                        default="fijo",
                        max_length=15,
                    ),
                ),
                ("base_salary", models.DecimalField(decimal_places=2, max_digits=14)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("activo", "Activo"),
                            ("vacaciones", "En Vacaciones"),
                            ("licencia", "En Licencia"),
                            ("incapacidad", "En Incapacidad"),
                            ("retirado", "Retirado"),
                        ],
                        default="activo",
                        max_length=15,
                    ),
                ),
                ("eps", models.CharField(blank=True, max_length=100)),
                ("arl", models.CharField(blank=True, max_length=100)),
                ("pension_fund", models.CharField(blank=True, max_length=100)),
                (
                    "photo",
                    models.ImageField(blank=True, null=True, upload_to="employees/"),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "department",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="employees",
                        to="personnel.department",
                    ),
                ),
            ],
            options={
                "verbose_name": "Empleado",
                "verbose_name_plural": "Empleados",
                "ordering": ["last_name", "first_name"],
            },
        ),
        migrations.CreateModel(
            name="EmployeeDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "doc_type",
                    models.CharField(
                        choices=[
                            ("contrato", "Contrato de Trabajo"),
                            ("cedula", "Cédula"),
                            ("hoja_vida", "Hoja de Vida"),
                            ("certificado", "Certificado"),
                            ("examen_medico", "Examen Médico"),
                            ("otro", "Otro"),
                        ],
                        max_length=20,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("file", models.FileField(upload_to="employees/documents/")),
                ("expiry_date", models.DateField(blank=True, null=True)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="personnel.employee",
                    ),
                ),
            ],
            options={
                "verbose_name": "Documento de Empleado",
                "verbose_name_plural": "Documentos de Empleados",
            },
        ),
        migrations.CreateModel(
            name="Position",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                ("description", models.TextField(blank=True)),
                (
                    "base_salary",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "department",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="positions",
                        to="personnel.department",
                    ),
                ),
            ],
            options={
                "verbose_name": "Cargo",
                "verbose_name_plural": "Cargos",
            },
        ),
        migrations.AddField(
            model_name="employee",
            name="position",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="employees",
                to="personnel.position",
            ),
        ),
    ]
