# Generated by Django 5.2.14 on 2026-05-12 03:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("projects", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "client_type",
                    models.CharField(
                        choices=[
                            ("publico", "Entidad Pública"),
                            ("privado", "Empresa Privada"),
                            ("persona_natural", "Persona Natural"),
                        ],
                        max_length=20,
                    ),
                ),
                ("nit", models.CharField(max_length=20, unique=True)),
                ("contact_person", models.CharField(blank=True, max_length=150)),
                ("phone", models.CharField(blank=True, max_length=20)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("address", models.CharField(blank=True, max_length=300)),
                ("city", models.CharField(blank=True, max_length=100)),
                ("is_active", models.BooleanField(default=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Cliente",
                "verbose_name_plural": "Clientes",
            },
        ),
        migrations.CreateModel(
            name="Contractor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("nit", models.CharField(max_length=20, unique=True)),
                (
                    "specialty",
                    models.CharField(
                        choices=[
                            ("concreto", "Concreto y Estructuras"),
                            ("electricidad", "Electricidad"),
                            ("plomeria", "Plomería e Hidrosanitaria"),
                            ("movimiento_tierras", "Movimiento de Tierras"),
                            ("pavimento", "Pavimentación"),
                            ("geotecnia", "Geotecnia"),
                            ("topografia", "Topografía"),
                            ("acabados", "Acabados"),
                            ("prefabricados", "Prefabricados"),
                            ("otro", "Otro"),
                        ],
                        max_length=20,
                    ),
                ),
                ("contact_person", models.CharField(blank=True, max_length=150)),
                ("phone", models.CharField(blank=True, max_length=20)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("address", models.CharField(blank=True, max_length=300)),
                ("city", models.CharField(blank=True, max_length=100)),
                ("is_active", models.BooleanField(default=True)),
                ("ruc", models.CharField(blank=True, max_length=30)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Contratista",
                "verbose_name_plural": "Contratistas",
            },
        ),
        migrations.CreateModel(
            name="Contract",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("contract_number", models.CharField(max_length=50, unique=True)),
                (
                    "contract_type",
                    models.CharField(
                        choices=[
                            ("principal", "Contrato Principal (Cliente)"),
                            ("subcontrato", "Subcontrato (Contratista)"),
                            ("suministro", "Contrato de Suministro"),
                            ("servicio", "Contrato de Servicio"),
                        ],
                        max_length=15,
                    ),
                ),
                ("description", models.TextField()),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("value", models.DecimalField(decimal_places=2, max_digits=18)),
                (
                    "advance_percentage",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "retention_percentage",
                    models.DecimalField(decimal_places=2, default=10, max_digits=5),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("borrador", "Borrador"),
                            ("revision", "En Revisión"),
                            ("firmado", "Firmado"),
                            ("en_ejecucion", "En Ejecución"),
                            ("terminado", "Terminado"),
                            ("liquidado", "Liquidado"),
                            ("anulado", "Anulado"),
                        ],
                        default="borrador",
                        max_length=15,
                    ),
                ),
                (
                    "contract_file",
                    models.FileField(blank=True, null=True, upload_to="contracts/"),
                ),
                ("signed_date", models.DateField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "client",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="contracts",
                        to="administration.client",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="contracts",
                        to="projects.project",
                    ),
                ),
                (
                    "contractor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="contracts",
                        to="administration.contractor",
                    ),
                ),
            ],
            options={
                "verbose_name": "Contrato",
                "verbose_name_plural": "Contratos",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ContractAddendum",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.IntegerField()),
                ("description", models.TextField()),
                (
                    "value_change",
                    models.DecimalField(decimal_places=2, default=0, max_digits=16),
                ),
                ("days_change", models.IntegerField(default=0)),
                ("signed_date", models.DateField()),
                (
                    "file",
                    models.FileField(
                        blank=True, null=True, upload_to="contracts/addenda/"
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "contract",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="addenda",
                        to="administration.contract",
                    ),
                ),
            ],
            options={
                "verbose_name": "Otrosí / Adición",
                "verbose_name_plural": "Otrosíes / Adiciones",
                "unique_together": {("contract", "number")},
            },
        ),
    ]
