# Generated by Django 5.2.14 on 2026-05-12 03:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("personnel", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PayrollPeriod",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "period_type",
                    models.CharField(
                        choices=[("quincenal", "Quincenal"), ("mensual", "Mensual")],
                        default="mensual",
                        max_length=10,
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("payment_date", models.DateField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("abierto", "Abierto"),
                            ("procesando", "Procesando"),
                            ("cerrado", "Cerrado"),
                            ("pagado", "Pagado"),
                        ],
                        default="abierto",
                        max_length=15,
                    ),
                ),
                (
                    "total_devengado",
                    models.DecimalField(decimal_places=2, default=0, max_digits=18),
                ),
                (
                    "total_deducciones",
                    models.DecimalField(decimal_places=2, default=0, max_digits=18),
                ),
                (
                    "total_neto",
                    models.DecimalField(decimal_places=2, default=0, max_digits=18),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Período de Nómina",
                "verbose_name_plural": "Períodos de Nómina",
                "ordering": ["-start_date"],
            },
        ),
        migrations.CreateModel(
            name="PayrollEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "days_worked",
                    models.DecimalField(decimal_places=2, default=30, max_digits=5),
                ),
                (
                    "regular_hours",
                    models.DecimalField(decimal_places=2, default=0, max_digits=6),
                ),
                (
                    "extra_hours_day",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "extra_hours_night",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "extra_hours_holiday",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                ("base_salary", models.DecimalField(decimal_places=2, max_digits=14)),
                (
                    "transportation_allowance",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "extra_pay",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "bonuses",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "vacation_pay",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "total_devengado",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "health_deduction",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "pension_deduction",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "other_deductions",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "advances",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "total_deductions",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "net_pay",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "employer_health",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "employer_pension",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "arl",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "ccf",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "icbf",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "sena",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payroll_entries",
                        to="personnel.employee",
                    ),
                ),
                (
                    "period",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="entries",
                        to="payroll.payrollperiod",
                    ),
                ),
            ],
            options={
                "verbose_name": "Entrada de Nómina",
                "verbose_name_plural": "Entradas de Nómina",
                "unique_together": {("period", "employee")},
            },
        ),
        migrations.CreateModel(
            name="SalaryAdvance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=14)),
                ("request_date", models.DateField()),
                ("reason", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pendiente", "Pendiente"),
                            ("aprobado", "Aprobado"),
                            ("rechazado", "Rechazado"),
                            ("descontado", "Descontado"),
                        ],
                        default="pendiente",
                        max_length=15,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="advances",
                        to="personnel.employee",
                    ),
                ),
                (
                    "payroll_entry",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="salary_advances",
                        to="payroll.payrollentry",
                    ),
                ),
            ],
            options={
                "verbose_name": "Anticipo de Salario",
                "verbose_name_plural": "Anticipos de Salario",
            },
        ),
    ]
